### PR TITLE
Change JuMP to MathProg and fix warnings

### LINKED ISSUE #19: Change JuMP to MPB
I'm doing this now.

### PR DESCRIPTION
**Pull request by abelsiqueira**
Closes #19

### CODE REVIEW

**Comment by abelsiqueira** [comment]
It should be fixed and ready to go.

File: src/Optimize.jl [hunk 1]
```diff
@@ -16,6 +17,6 @@ include("solver/solver.jl")
 # Utilities.
 include("bmark/run_solver.jl")
 include("bmark/bmark_solvers.jl")
-include("bmark/jump_vs_ampl.jl")
+include("bmark/mpb_vs_ampl.jl")
```
Comment (dpo) [inline src/Optimize.jl]: If we're not requiring JuMP, then this should only be `include`d if MathProgBase is available.

**Comment by abelsiqueira** [comment]
Done
